config:
  info: "config info for test(master)"

server:
  port: 3355
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      
spring:
  application:
    name: microservicecloud-config-client2
